[{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"syncActTo1CInDB\".",
	"source": "ts",
	"startLineNumber": 250,
	"startColumn": 5,
	"endLineNumber": 250,
	"endColumn": 20,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "Ожидалось \")\".",
	"source": "ts",
	"startLineNumber": 792,
	"startColumn": 11,
	"endLineNumber": 792,
	"endColumn": 13,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"div\".",
	"source": "ts",
	"startLineNumber": 792,
	"startColumn": 13,
	"endLineNumber": 792,
	"endColumn": 16,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2657",
	"severity": 8,
	"message": "Выражения JSX должны иметь один родительский элемент.",
	"source": "ts",
	"startLineNumber": 794,
	"startColumn": 11,
	"endLineNumber": 869,
	"endColumn": 17,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "1128",
	"severity": 8,
	"message": "Ожидалось объявление или оператор.",
	"source": "ts",
	"startLineNumber": 871,
	"startColumn": 9,
	"endLineNumber": 871,
	"endColumn": 11,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"div\".",
	"source": "ts",
	"startLineNumber": 871,
	"startColumn": 11,
	"endLineNumber": 871,
	"endColumn": 14,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Ожидалось выражение.",
	"source": "ts",
	"startLineNumber": 872,
	"startColumn": 7,
	"endLineNumber": 872,
	"endColumn": 8,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"currentUser\".",
	"source": "ts",
	"startLineNumber": 875,
	"startColumn": 8,
	"endLineNumber": 875,
	"endColumn": 19,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"handleIngestSupply\".",
	"source": "ts",
	"startLineNumber": 887,
	"startColumn": 29,
	"endLineNumber": 887,
	"endColumn": 47,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"selectedSupplier\".",
	"source": "ts",
	"startLineNumber": 892,
	"startColumn": 26,
	"endLineNumber": 892,
	"endColumn": 42,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"setSelectedSupplier\".",
	"source": "ts",
	"startLineNumber": 893,
	"startColumn": 36,
	"endLineNumber": 893,
	"endColumn": 55,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"dbState\".",
	"source": "ts",
	"startLineNumber": 898,
	"startColumn": 20,
	"endLineNumber": 898,
	"endColumn": 27,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Параметр \"s\" неявно имеет тип \"any\".",
	"source": "ts",
	"startLineNumber": 898,
	"startColumn": 42,
	"endLineNumber": 898,
	"endColumn": 43,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"selectedProduct\".",
	"source": "ts",
	"startLineNumber": 907,
	"startColumn": 26,
	"endLineNumber": 907,
	"endColumn": 41,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"setSelectedProduct\".",
	"source": "ts",
	"startLineNumber": 908,
	"startColumn": 36,
	"endLineNumber": 908,
	"endColumn": 54,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"dbState\".",
	"source": "ts",
	"startLineNumber": 913,
	"startColumn": 20,
	"endLineNumber": 913,
	"endColumn": 27,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Параметр \"p\" неявно имеет тип \"any\".",
	"source": "ts",
	"startLineNumber": 913,
	"startColumn": 41,
	"endLineNumber": 913,
	"endColumn": 42,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"supplyQty\".",
	"source": "ts",
	"startLineNumber": 924,
	"startColumn": 26,
	"endLineNumber": 924,
	"endColumn": 35,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"setSupplyQty\".",
	"source": "ts",
	"startLineNumber": 925,
	"startColumn": 36,
	"endLineNumber": 925,
	"endColumn": 48,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"supplyManDate\".",
	"source": "ts",
	"startLineNumber": 935,
	"startColumn": 26,
	"endLineNumber": 935,
	"endColumn": 39,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"setSupplyManDate\".",
	"source": "ts",
	"startLineNumber": 936,
	"startColumn": 36,
	"endLineNumber": 936,
	"endColumn": 52,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"supplyExpDate\".",
	"source": "ts",
	"startLineNumber": 945,
	"startColumn": 26,
	"endLineNumber": 945,
	"endColumn": 39,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"setSupplyExpDate\".",
	"source": "ts",
	"startLineNumber": 946,
	"startColumn": 36,
	"endLineNumber": 946,
	"endColumn": 52,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"supplyLocation\".",
	"source": "ts",
	"startLineNumber": 955,
	"startColumn": 26,
	"endLineNumber": 955,
	"endColumn": 40,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"setSupplyLocation\".",
	"source": "ts",
	"startLineNumber": 956,
	"startColumn": 36,
	"endLineNumber": 956,
	"endColumn": 53,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"dbState\".",
	"source": "ts",
	"startLineNumber": 959,
	"startColumn": 20,
	"endLineNumber": 959,
	"endColumn": 27,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Параметр \"loc\" неявно имеет тип \"any\".",
	"source": "ts",
	"startLineNumber": 959,
	"startColumn": 48,
	"endLineNumber": 959,
	"endColumn": 51,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"dbState\".",
	"source": "ts",
	"startLineNumber": 990,
	"startColumn": 16,
	"endLineNumber": 990,
	"endColumn": 23,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Параметр \"sup\" неявно имеет тип \"any\".",
	"source": "ts",
	"startLineNumber": 990,
	"startColumn": 38,
	"endLineNumber": 990,
	"endColumn": 41,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"currentUser\".",
	"source": "ts",
	"startLineNumber": 1010,
	"startColumn": 8,
	"endLineNumber": 1010,
	"endColumn": 19,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"tsdSelectedProduct\".",
	"source": "ts",
	"startLineNumber": 1027,
	"startColumn": 26,
	"endLineNumber": 1027,
	"endColumn": 44,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"setTsdSelectedProduct\".",
	"source": "ts",
	"startLineNumber": 1028,
	"startColumn": 36,
	"endLineNumber": 1028,
	"endColumn": 57,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"dbState\".",
	"source": "ts",
	"startLineNumber": 1032,
	"startColumn": 20,
	"endLineNumber": 1032,
	"endColumn": 27,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Параметр \"p\" неявно имеет тип \"any\".",
	"source": "ts",
	"startLineNumber": 1032,
	"startColumn": 41,
	"endLineNumber": 1032,
	"endColumn": 42,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"tsdSelectedProduct\".",
	"source": "ts",
	"startLineNumber": 1038,
	"startColumn": 16,
	"endLineNumber": 1038,
	"endColumn": 34,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"dbState\".",
	"source": "ts",
	"startLineNumber": 1040,
	"startColumn": 32,
	"endLineNumber": 1040,
	"endColumn": 39,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Параметр \"p\" неявно имеет тип \"any\".",
	"source": "ts",
	"startLineNumber": 1040,
	"startColumn": 54,
	"endLineNumber": 1040,
	"endColumn": 55,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"tsdSelectedProduct\".",
	"source": "ts",
	"startLineNumber": 1040,
	"startColumn": 68,
	"endLineNumber": 1040,
	"endColumn": 86,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"dbState\".",
	"source": "ts",
	"startLineNumber": 1041,
	"startColumn": 33,
	"endLineNumber": 1041,
	"endColumn": 40,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Параметр \"b\" неявно имеет тип \"any\".",
	"source": "ts",
	"startLineNumber": 1041,
	"startColumn": 56,
	"endLineNumber": 1041,
	"endColumn": 57,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"tsdSelectedProduct\".",
	"source": "ts",
	"startLineNumber": 1041,
	"startColumn": 78,
	"endLineNumber": 1041,
	"endColumn": 96,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Параметр \"s\" неявно имеет тип \"any\".",
	"source": "ts",
	"startLineNumber": 1042,
	"startColumn": 50,
	"endLineNumber": 1042,
	"endColumn": 51,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Параметр \"b\" неявно имеет тип \"any\".",
	"source": "ts",
	"startLineNumber": 1042,
	"startColumn": 53,
	"endLineNumber": 1042,
	"endColumn": 54,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"handleTsdMarkdown\".",
	"source": "ts",
	"startLineNumber": 1066,
	"startColumn": 32,
	"endLineNumber": 1066,
	"endColumn": 49,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"tsdSelectedProduct\".",
	"source": "ts",
	"startLineNumber": 1067,
	"startColumn": 28,
	"endLineNumber": 1067,
	"endColumn": 46,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"handleTsdMarkdown\".",
	"source": "ts",
	"startLineNumber": 1073,
	"startColumn": 32,
	"endLineNumber": 1073,
	"endColumn": 49,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"tsdSelectedProduct\".",
	"source": "ts",
	"startLineNumber": 1074,
	"startColumn": 28,
	"endLineNumber": 1074,
	"endColumn": 46,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"handleTsdWriteOff\".",
	"source": "ts",
	"startLineNumber": 1080,
	"startColumn": 26,
	"endLineNumber": 1080,
	"endColumn": 43,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"tsdSelectedProduct\".",
	"source": "ts",
	"startLineNumber": 1081,
	"startColumn": 28,
	"endLineNumber": 1081,
	"endColumn": 46,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"salesSimulationActive\".",
	"source": "ts",
	"startLineNumber": 1101,
	"startColumn": 30,
	"endLineNumber": 1101,
	"endColumn": 51,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"setSalesSimulationActive\".",
	"source": "ts",
	"startLineNumber": 1102,
	"startColumn": 38,
	"endLineNumber": 1102,
	"endColumn": 62,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"salesSimulationActive\".",
	"source": "ts",
	"startLineNumber": 1106,
	"startColumn": 33,
	"endLineNumber": 1106,
	"endColumn": 54,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"posSelectedBatch\".",
	"source": "ts",
	"startLineNumber": 1119,
	"startColumn": 28,
	"endLineNumber": 1119,
	"endColumn": 44,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"setPosSelectedBatch\".",
	"source": "ts",
	"startLineNumber": 1120,
	"startColumn": 38,
	"endLineNumber": 1120,
	"endColumn": 57,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"dbState\".",
	"source": "ts",
	"startLineNumber": 1124,
	"startColumn": 22,
	"endLineNumber": 1124,
	"endColumn": 29,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Параметр \"b\" неявно имеет тип \"any\".",
	"source": "ts",
	"startLineNumber": 1124,
	"startColumn": 45,
	"endLineNumber": 1124,
	"endColumn": 46,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Параметр \"b\" неявно имеет тип \"any\".",
	"source": "ts",
	"startLineNumber": 1124,
	"startColumn": 70,
	"endLineNumber": 1124,
	"endColumn": 71,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"dbState\".",
	"source": "ts",
	"startLineNumber": 1125,
	"startColumn": 36,
	"endLineNumber": 1125,
	"endColumn": 43,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Параметр \"p\" неявно имеет тип \"any\".",
	"source": "ts",
	"startLineNumber": 1125,
	"startColumn": 58,
	"endLineNumber": 1125,
	"endColumn": 59,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"posQty\".",
	"source": "ts",
	"startLineNumber": 1141,
	"startColumn": 30,
	"endLineNumber": 1141,
	"endColumn": 36,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"setPosQty\".",
	"source": "ts",
	"startLineNumber": 1142,
	"startColumn": 40,
	"endLineNumber": 1142,
	"endColumn": 49,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"handleManualSale\".",
	"source": "ts",
	"startLineNumber": 1149,
	"startColumn": 32,
	"endLineNumber": 1149,
	"endColumn": 48,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"posSelectedBatch\".",
	"source": "ts",
	"startLineNumber": 1150,
	"startColumn": 34,
	"endLineNumber": 1150,
	"endColumn": 50,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"tsdStatusMessage\".",
	"source": "ts",
	"startLineNumber": 1181,
	"startColumn": 18,
	"endLineNumber": 1181,
	"endColumn": 34,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"tsdStatusMessage\".",
	"source": "ts",
	"startLineNumber": 1183,
	"startColumn": 31,
	"endLineNumber": 1183,
	"endColumn": 47,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"liveSalesJournal\".",
	"source": "ts",
	"startLineNumber": 1187,
	"startColumn": 18,
	"endLineNumber": 1187,
	"endColumn": 34,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"liveSalesJournal\".",
	"source": "ts",
	"startLineNumber": 1192,
	"startColumn": 19,
	"endLineNumber": 1192,
	"endColumn": 35,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Параметр \"item\" неявно имеет тип \"any\".",
	"source": "ts",
	"startLineNumber": 1192,
	"startColumn": 40,
	"endLineNumber": 1192,
	"endColumn": 44,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"dbState\".",
	"source": "ts",
	"startLineNumber": 1204,
	"startColumn": 21,
	"endLineNumber": 1204,
	"endColumn": 28,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Параметр \"log\" неявно имеет тип \"any\".",
	"source": "ts",
	"startLineNumber": 1204,
	"startColumn": 69,
	"endLineNumber": 1204,
	"endColumn": 72,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"dbState\".",
	"source": "ts",
	"startLineNumber": 1205,
	"startColumn": 33,
	"endLineNumber": 1205,
	"endColumn": 40,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Параметр \"e\" неявно имеет тип \"any\".",
	"source": "ts",
	"startLineNumber": 1205,
	"startColumn": 56,
	"endLineNumber": 1205,
	"endColumn": 57,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "1128",
	"severity": 8,
	"message": "Ожидалось объявление или оператор.",
	"source": "ts",
	"startLineNumber": 1221,
	"startColumn": 5,
	"endLineNumber": 1221,
	"endColumn": 7,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Не удается найти имя \"div\".",
	"source": "ts",
	"startLineNumber": 1221,
	"startColumn": 7,
	"endLineNumber": 1221,
	"endColumn": 10,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Ожидалось выражение.",
	"source": "ts",
	"startLineNumber": 1222,
	"startColumn": 3,
	"endLineNumber": 1222,
	"endColumn": 4,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/b:/Провода/Practic2.2/src/components/RoleWorkspace.tsx",
	"owner": "typescript",
	"code": "1128",
	"severity": 8,
	"message": "Ожидалось объявление или оператор.",
	"source": "ts",
	"startLineNumber": 1223,
	"startColumn": 1,
	"endLineNumber": 1223,
	"endColumn": 2,
	"modelVersionId": 14,
	"origin": "extHost1"
}]